import type { ManifestSchema, WorkflowPhase } from '../phase-types.js';
import * as fs from 'fs-extra';
import * as path from 'path';

/**
 * Operations Phase Templates
 *
 * Template-based artifact generation for the Operations (deployment/operations) phase.
 * v1: documentation generation only, no actual deployment.
 */

export interface OperationsContext {
  workflowId: string;
  featureName: string;
  manifest: ManifestSchema | null;
  specContent: string | null;
  buildLogContent: string | null;
  depthLevel: 'SHALLOW' | 'MEDIUM' | 'DEEP';
}

/** @deprecated Use OperationsContext */
export type SummitContext = OperationsContext;

/**
 * Generate deployment guide markdown
 */
export function generateDeployGuide(context: OperationsContext): string {
  const { featureName, workflowId, manifest } = context;
  const timestamp = new Date().toISOString();
  const totalArtifacts = manifest?.artifacts?.length ?? 0;
  const inceptionArtifacts = manifest?.artifacts?.filter(a => a.phase === 'inception').length ?? 0;
  const constructionArtifacts = manifest?.artifacts?.filter(a => a.phase === 'construction').length ?? 0;

  return `---
id: DEPLOY-GUIDE-001
feature: ${workflowId}
created: ${timestamp}
phase: operations
stage: deploy
---

# Deployment Guide: ${featureName}

## Overview

This deployment guide documents the deployment process for ${featureName}.
Generated from ${totalArtifacts} artifacts (${inceptionArtifacts} Inception, ${constructionArtifacts} Construction).

## Pre-Deployment Checklist

- [ ] All Inception artifacts validated and approved
- [ ] All Construction artifacts built and tested
- [ ] Integration tests passing
- [ ] Code review completed
- [ ] Security scan passed
- [ ] Performance benchmarks met

## Deployment Steps

### 1. Pre-Deployment

1. Verify all quality gates have been passed
2. Confirm deployment window with stakeholders
3. Prepare rollback plan
4. Notify affected teams

### 2. Deployment Execution

1. Deploy database migrations (if applicable)
2. Deploy backend services
3. Deploy frontend assets
4. Verify health checks
5. Run smoke tests

### 3. Post-Deployment

1. Monitor error rates for 30 minutes
2. Verify key user flows
3. Check performance metrics
4. Confirm with stakeholders

## Rollback Procedure

1. Identify deployment issue
2. Execute rollback for affected services
3. Verify system stability
4. Investigate root cause
5. Document incident

## Environment Configuration

| Environment | Purpose | Deployment Method |
|-------------|---------|-------------------|
| Development | Feature development | Automatic on merge |
| Staging | Pre-production testing | Manual trigger |
| Production | Live users | Manual approval |

---
*Generated by Operations Phase Templates*
`;
}

/**
 * Generate runbook markdown
 */
export function generateRunbook(context: OperationsContext): string {
  const { featureName, workflowId } = context;
  const timestamp = new Date().toISOString();

  return `---
id: RUNBOOK-001
feature: ${workflowId}
created: ${timestamp}
phase: operations
stage: deploy
---

# Runbook: ${featureName}

## Service Overview

**Feature**: ${featureName}
**Workflow ID**: ${workflowId}

## Common Operations

### Health Check

\`\`\`bash
# Check service health
curl -f http://localhost:PORT/health || echo "Service unhealthy"
\`\`\`

### Log Access

\`\`\`bash
# View recent logs
tail -f /var/log/service/${workflowId}.log

# Search for errors
grep -i error /var/log/service/${workflowId}.log | tail -20
\`\`\`

### Restart Procedure

1. Graceful shutdown: Send SIGTERM
2. Wait for connections to drain (30s timeout)
3. Start new instance
4. Verify health check passes
5. Route traffic to new instance

## Troubleshooting

### High Error Rate

1. Check application logs for stack traces
2. Verify database connectivity
3. Check external service dependencies
4. Review recent deployments
5. Escalate if unresolved after 15 minutes

### High Latency

1. Check database query performance
2. Verify cache hit rates
3. Check connection pool utilization
4. Review resource utilization (CPU, memory)
5. Scale horizontally if needed

### Service Unavailable

1. Check if process is running
2. Verify port binding
3. Check disk space
4. Review memory usage
5. Restart service if needed

## Escalation Path

| Level | Contact | Response Time |
|-------|---------|---------------|
| L1 | On-call engineer | 15 minutes |
| L2 | Team lead | 30 minutes |
| L3 | Engineering manager | 1 hour |

## Maintenance Windows

- **Scheduled**: Tuesdays 2-4 AM UTC
- **Emergency**: As needed with stakeholder approval
- **Database migrations**: During scheduled maintenance only

---
*Generated by Operations Phase Templates*
`;
}

/**
 * Generate monitoring configuration JSON
 */
export function generateMonitoringConfig(context: OperationsContext): string {
  const { featureName, workflowId, manifest } = context;
  const timestamp = new Date().toISOString();
  const riskTier = manifest?.risk_tier?.tier ?? 2;

  // Higher risk tier = more aggressive monitoring
  const errorThreshold = riskTier === 3 ? 0.5 : riskTier === 2 ? 1 : 2;
  const latencyThreshold = riskTier === 3 ? 500 : riskTier === 2 ? 1000 : 2000;
  const checkInterval = riskTier === 3 ? 30 : riskTier === 2 ? 60 : 120;

  const config = {
    id: 'MONITORING-001',
    feature: workflowId,
    feature_name: featureName,
    created: timestamp,
    phase: 'operations' as const,
    stage: 'monitor' as const,
    risk_tier: riskTier,
    health_checks: {
      endpoint: `/health`,
      interval_seconds: checkInterval,
      timeout_seconds: 5,
      unhealthy_threshold: 3,
    },
    alerts: [
      {
        name: `${workflowId}-error-rate`,
        metric: 'error_rate_percent',
        threshold: errorThreshold,
        window_seconds: 300,
        severity: 'critical',
        notification_channels: ['pagerduty', 'slack'],
      },
      {
        name: `${workflowId}-latency-p99`,
        metric: 'latency_p99_ms',
        threshold: latencyThreshold,
        window_seconds: 300,
        severity: 'warning',
        notification_channels: ['slack'],
      },
      {
        name: `${workflowId}-availability`,
        metric: 'availability_percent',
        threshold: 99.9,
        comparison: 'less_than',
        window_seconds: 3600,
        severity: 'critical',
        notification_channels: ['pagerduty', 'slack'],
      },
    ],
    dashboards: {
      overview: {
        panels: [
          { title: 'Request Rate', metric: 'request_rate', type: 'timeseries' },
          { title: 'Error Rate', metric: 'error_rate_percent', type: 'timeseries' },
          { title: 'Latency (p50/p95/p99)', metric: 'latency_percentiles', type: 'timeseries' },
          { title: 'Availability', metric: 'availability_percent', type: 'stat' },
        ],
      },
    },
    logging: {
      level: riskTier === 3 ? 'debug' : 'info',
      retention_days: riskTier === 3 ? 90 : riskTier === 2 ? 60 : 30,
      structured: true,
    },
  };

  return JSON.stringify(config, null, 2);
}

/**
 * Generate release notes markdown
 */
export function generateReleaseNotes(context: OperationsContext): string {
  const { featureName, workflowId, manifest } = context;
  const timestamp = new Date().toISOString();
  const artifacts = manifest?.artifacts ?? [];
  const inceptionArtifacts = artifacts.filter(a => a.phase === 'inception');
  const constructionArtifacts = artifacts.filter(a => a.phase === 'construction');
  const risks = manifest?.risks ?? [];
  const openRisks = risks.filter(r => r.status === 'open');
  const mitigatedRisks = risks.filter(r => r.status === 'mitigated');
  const gateAudit = manifest?.gate_audit ?? [];
  const approvedGates = gateAudit.filter(g => g.action === 'approved');

  // Build artifact summary lines
  const artifactLines = artifacts.map(a => `- **${a.id}** (${a.phase}/${a.stage}): ${a.contract_status}`).join('\n');

  return `---
id: RELEASE-NOTES-001
feature: ${workflowId}
created: ${timestamp}
phase: operations
stage: deploy
---

# Release Notes: ${featureName}

## Summary

**Feature**: ${featureName}
**Workflow ID**: ${workflowId}
**Date**: ${timestamp.split('T')[0]}
**Total Artifacts**: ${artifacts.length}
**Quality Gates Passed**: ${approvedGates.length}

## What's New

Implementation of ${featureName} following the Olympus Development Life Cycle (ODLC) methodology.

### Inception Phase (${inceptionArtifacts.length} artifacts)
- IDEA: Problem definition and depth assessment
- PRD: Product requirements with user stories
- SPEC: Technical specification and architecture
- INTENTS: Implementation task breakdown

### Construction Phase (${constructionArtifacts.length} artifacts)
- Units: Architectural component decomposition
- Design: Interface contracts and data flow
- Bolts: Atomic implementation tasks

## Artifacts

${artifactLines || '- No artifacts registered'}

## Risk Status

- **Open Risks**: ${openRisks.length}
- **Mitigated Risks**: ${mitigatedRisks.length}
- **Total Risks**: ${risks.length}

${openRisks.length > 0 ? '### Open Risks\n' + openRisks.map(r => `- **${r.id}**: ${r.description} (${r.likelihood}/${r.impact})`).join('\n') : ''}

## Quality Assurance

- **Gates Passed**: ${approvedGates.length}
- **Methodology**: ODLC (Inception → Construction → Operations)
- **Risk Tier**: ${manifest?.risk_tier?.tier ?? 'Not assessed'}

## Known Issues

- Operations phase is documentation-only in v1
- No automated deployment execution
- Monitoring configuration requires manual setup

## Upgrade Notes

This is a new feature deployment. No migration from previous versions required.

---
*Generated by Operations Phase Templates*
`;
}

/**
 * Generate cost analysis markdown
 */
export function generateCostAnalysis(context: OperationsContext): string {
  const { featureName, workflowId, manifest } = context;
  const timestamp = new Date().toISOString();
  const artifacts = manifest?.artifacts ?? [];
  const bolts = artifacts.filter(a => a.stage === 'bolt');
  const units = artifacts.filter(a => a.stage === 'unit');
  const gateAudit = manifest?.gate_audit ?? [];
  const rejections = gateAudit.filter(g => g.action === 'rejected');
  const metrics = manifest?.metrics ?? null;

  return `---
id: COST-001
feature: ${workflowId}
created: ${timestamp}
phase: operations
---

# Cost Analysis: ${featureName}

## Workflow Metrics

| Metric | Value |
|--------|-------|
| Total UNITs | ${units.length} |
| Total BOLTs | ${bolts.length} |
| Gate Rejections | ${rejections.length} |
| Total Artifacts | ${artifacts.length} |

## Agent Execution Summary

${metrics ? `
| Phase | Duration (ms) |
|-------|---------------|
| Inception | ${metrics.inception_duration_ms ?? 'N/A'} |
| Construction | ${metrics.construction_duration_ms ?? 'N/A'} |
| Operations | ${metrics.operations_duration_ms ?? 'N/A'} |
| Rework Cycles | ${metrics.rework_count} |
| Validation Pass Rate | ${(metrics.validation_pass_rate * 100).toFixed(1)}% |
` : 'No metrics recorded for this workflow.'}

## Rework Cost

${rejections.length > 0 ? `
Gate rejections indicate rework cycles:
${rejections.map(r => `- **${r.phase}** (${r.timestamp}): ${r.reason || 'No reason provided'}`).join('\n')}

Estimated rework overhead: ${rejections.length} rejection cycle(s)
` : 'No gate rejections — zero rework cycles.'}

## Recommendations

${bolts.length > 10 ? '- Consider breaking future features into smaller INTENTs to reduce BOLT count' : '- BOLT count is within recommended range'}
${rejections.length > 2 ? '- High rejection rate suggests specification clarity could be improved' : '- Rejection rate is acceptable'}

---
*Generated by Operations Phase Templates*
`;
}

/**
 * Result of operations artifact generation
 */
export interface OperationsResult {
  artifactsGenerated: string[];
  operationsDir: string;
}

/**
 * Generate all Operations phase artifacts based on depth level.
 *
 * SHALLOW workflows generate only release-notes.md.
 * MEDIUM/DEEP workflows generate all 5 artifacts.
 *
 * @param context - Operations context with depth awareness
 * @param projectPath - Absolute path to project root
 * @returns List of generated artifact filenames and output directory
 */
export async function generateOperationsArtifacts(
  context: OperationsContext,
  projectPath: string
): Promise<OperationsResult> {
  const operationsDir = path.join(projectPath, 'aidlc-docs', 'operations');
  await fs.ensureDir(operationsDir);

  const generated: string[] = [];
  const depth = context.depthLevel || 'MEDIUM';

  // Release notes always generated
  await fs.writeFile(
    path.join(operationsDir, 'release-notes.md'),
    generateReleaseNotes(context),
    'utf-8'
  );
  generated.push('release-notes.md');

  // SHALLOW: only release notes
  if (depth === 'SHALLOW') {
    return { artifactsGenerated: generated, operationsDir };
  }

  // MEDIUM/DEEP: generate all artifacts
  await fs.writeFile(
    path.join(operationsDir, 'deploy-guide.md'),
    generateDeployGuide(context),
    'utf-8'
  );
  generated.push('deploy-guide.md');

  await fs.writeFile(
    path.join(operationsDir, 'runbook.md'),
    generateRunbook(context),
    'utf-8'
  );
  generated.push('runbook.md');

  await fs.writeFile(
    path.join(operationsDir, 'monitoring.json'),
    generateMonitoringConfig(context),
    'utf-8'
  );
  generated.push('monitoring.json');

  await fs.writeFile(
    path.join(operationsDir, 'cost.md'),
    generateCostAnalysis(context),
    'utf-8'
  );
  generated.push('cost.md');

  return { artifactsGenerated: generated, operationsDir };
}
