/**
 * esbuild Configuration for Olympus Hooks Bundle
 *
 * Bundles all hooks into a single self-contained file.
 */
import * as esbuild from 'esbuild';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outdir = join(__dirname, 'dist', 'hooks');

// Ensure output directory exists
if (!existsSync(outdir)) {
  mkdirSync(outdir, { recursive: true });
}

await esbuild.build({
  entryPoints: ['src/hooks/entry.ts'],
  bundle: true,
  outfile: join(outdir, 'olympus-hooks.cjs'),
  format: 'cjs',  // Use CommonJS format to avoid ESM/CJS interop issues
  platform: 'node',
  target: 'node18',
  minify: true,  // Minify for production
  sourcemap: false,
  // Prefer ESM modules over UMD/CommonJS to avoid bundling issues
  mainFields: ['module', 'main'],
  // Bundle all dependencies except Node.js built-ins
  external: ['node:*', 'fs', 'path', 'os', 'crypto', 'child_process', 'util', 'stream', 'events', 'buffer', 'url', 'assert', 'http', 'https', 'net', 'tls', 'dns', 'readline', 'zlib', 'diagnostics_channel'],
  define: {
    'process.env.NODE_ENV': '"production"'
  },
  banner: {
    js: '// Olympus Hooks Bundle - Generated by esbuild'
  }
});

// Post-process to ensure single shebang and banner
const outfile = join(outdir, 'olympus-hooks.cjs');
let content = readFileSync(outfile, 'utf-8');

// Split into lines, remove duplicates
const lines = content.split('\n');
const filtered = [];
let seenBanner = false;

for (const line of lines) {
  // Skip duplicate banners
  if (line.startsWith('// Olympus Hooks Bundle')) {
    if (seenBanner) continue;
    seenBanner = true;
  }
  filtered.push(line);
}

content = filtered.join('\n');

// Ensure shebang is first
if (!content.startsWith('#!')) {
  content = `#!/usr/bin/env node\n${content}`;
}

writeFileSync(outfile, content, 'utf-8');

console.log('Built: dist/hooks/olympus-hooks.cjs');
